/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutEventsIndexRouteImport } from './routes/_layout/events/index'
import { Route as LayoutEventsEventIdRouteImport } from './routes/_layout/events/$eventId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsIndexRoute = LayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsEventIdRoute = LayoutEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/events/$eventId': typeof LayoutEventsEventIdRoute
  '/events/': typeof LayoutEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/events/$eventId': typeof LayoutEventsEventIdRoute
  '/events': typeof LayoutEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/events/$eventId': typeof LayoutEventsEventIdRoute
  '/_layout/events/': typeof LayoutEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/$eventId' | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$eventId' | '/events'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/events/$eventId'
    | '/_layout/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/': {
      id: '/_layout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof LayoutEventsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events/$eventId': {
      id: '/_layout/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof LayoutEventsEventIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutEventsEventIdRoute: typeof LayoutEventsEventIdRoute
  LayoutEventsIndexRoute: typeof LayoutEventsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutEventsEventIdRoute: LayoutEventsEventIdRoute,
  LayoutEventsIndexRoute: LayoutEventsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
